TimManager/Models/LogViewer/LogEventType.cs
namespace TimManager.Models.LogViewer
{
    public enum LogEvent
    {
        Undefined,
        Trace,
        Debug,
        Info,
        Warn,
        Error,
        Fatal,
    }
}

TimManager/Models/LogViewer/LogViewerViewModel.cs
using System.Collections.Generic;
using System.Linq;
using TimManager.LogViewer;

namespace TimManager.Models.LogViewer
{
    public class LogViewerViewModel
    {
        public ICollection<LogItem> LogItems { get; }

        public int LogItemsCount => LogItems.Count;
        
        public int LogItemsUndefinedCount => LogItems.Count(l => l.LogEvent == LogEvent.Undefined);
        public int LogItemsTraceCount => LogItems.Count(l => l.LogEvent == LogEvent.Trace);
        public int LogItemsDebugCount => LogItems.Count(l => l.LogEvent == LogEvent.Debug);
        public int LogItemsInfoCount => LogItems.Count(l => l.LogEvent == LogEvent.Info);
        public int LogItemsWarnCount => LogItems.Count(l => l.LogEvent == LogEvent.Warn);
        public int LogItemsErrorCount => LogItems.Count(l => l.LogEvent == LogEvent.Error);
        public int LogItemsFatalCount => LogItems.Count(l => l.LogEvent == LogEvent.Fatal);

        public LogViewerViewModel(ICollection<LogItem> logItems = null)
        {
            LogItems = logItems ?? new List<LogItem>();
            
        }
    }
}

TimManager/Controllers/LogViewerController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using TimManager.LogViewer;
using TimManager.LogViewer.SearchLog;
using TimManager.Models.LogViewer;

namespace TimManager.Controllers
{
    public class LogViewerController : Controller
    {
        private readonly LogViewer.LogViewer _logViewer;
        private readonly LogItemRepository _logItemRepository;
        private const string REGEXP_PATTERN = "(?<DateTime>\\d*\\/\\d*\\/\\d* \\d*:\\d*:.*) \\[(?<LogEvent>.*)\\] \\[(?<ThreadName>.*)\\] (?<Callsite>.*) - (?<Message>.*)";

        public LogViewerController(IWebHostEnvironment environment)
        {
            _logViewer = new LogViewer.LogViewer();
            _logItemRepository = new LogItemRepository(environment.WebRootPath);
        }

        // GET
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Build(IFormFile uploadedFile)
        {
            if (uploadedFile == null)
                throw new ArgumentNullException(nameof(uploadedFile));

            RegexBuilderLogItem regexBuilderLogItem = new RegexBuilderLogItem(REGEXP_PATTERN);
            var openReadStream = uploadedFile.OpenReadStream();
            List<LogItem> logItems = await _logViewer.ExtractLines(openReadStream, regexBuilderLogItem);

            await _logItemRepository.SaveAsync(uploadedFile.FileName, logItems);

            return View(new LogViewerViewModel(logItems));
        }
    }
}

TimManager/Views/LogViewer/Build.cshtml
@using TimManager.Models.LogViewer
@using TimManager.LogViewer
@model LogViewerViewModel
@{
    ViewBag.Title = "Logs";
}

<div class="container-fluid">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3">Fluid jumbotron</h1>
            <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-sm">
            <div class="sticky-top top-15">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Записей</th>
                        <th scope="col">Кол-во</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">Total</th>
                        <td>@Model.LogItemsCount</td>
                    </tr>
                    <tr data-level="@LogEvent.Undefined">
                        <th scope="row">Undefined</th>
                        <td>@Model.LogItemsUndefinedCount</td>
                    </tr>
                    <tr data-level="@LogEvent.Trace">
                        <th scope="row">Trace</th>
                        <td>@Model.LogItemsTraceCount</td>
                    </tr>
                    <tr data-level="@LogEvent.Debug">
                        <th scope="row">Debug</th>
                        <td>@Model.LogItemsDebugCount</td>
                    </tr>
                    <tr data-level="@LogEvent.Info">
                        <th scope="row">Info</th>
                        <td>@Model.LogItemsInfoCount</td>
                    </tr>
                    <tr data-level="@LogEvent.Warn">
                        <th scope="row">Warning</th>
                        <td>@Model.LogItemsWarnCount</td>
                    </tr>
                    <tr data-level="@LogEvent.Error">
                        <th scope="row">Error</th>
                        <td>@Model.LogItemsErrorCount</td>
                    </tr>
                    <tr data-level="@LogEvent.Fatal">
                        <th scope="row">Fatal</th>
                        <td>@Model.LogItemsFatalCount</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-8">
            <table class="table table-responsive table-striped table-hover">
                <thead>
                <tr>
                    <th>DateTime</th>
                    <th>LogEvent</th>
                    <th>Message</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.LogItems)
                {
                    <tr data-level="@item.LogEvent" data-id="@item.Id">
                        <td>@item.DateTime</td>
                        <td>@item.LogEvent</td>
                        <td>@item.Message</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>

        @* TODO *@
        <div class="col">
            <div class="sticky-top bg-info top-15">
                <ul class="list-group">
                  <li class="list-group-item">Dapibus ac facilisis in</li>
                  
                  <li class="list-group-item list-group-item-primary">This is a primary list group item</li>
                  <li class="list-group-item list-group-item-secondary">This is a secondary list group item</li>
                  <li class="list-group-item list-group-item-success">This is a success list group item</li>
                  <li class="list-group-item list-group-item-danger">This is a danger list group item</li>
                  <li class="list-group-item list-group-item-warning">This is a warning list group item</li>
                  <li class="list-group-item list-group-item-info">This is a info list group item</li>
                  <li class="list-group-item list-group-item-light">This is a light list group item</li>
                  <li class="list-group-item list-group-item-dark">This is a dark list group item</li>
                </ul>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script type="text/javascript" src="@Url.Content("/js/LogViewer/Index.js")"></script>
}

TimManager/Views/LogViewer/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container">
    @using (Html.BeginForm("Build", "LogViewer", FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        <dl>
            <dt>
                <label for="FileUpload_FormFile">File</label>
            </dt>
            <dd>
                <input id="FileUpload_FormFile"
                       type="file"
                       accept=".txt"
                       name="uploadedFile"/>
            </dd>
        </dl>
        <input type="submit" value="Import"/>
    }
</div>