TimManager/Areas/Identity/Controllers/PassItemsController.cs
using System;
using System.Collections.Generic;
using System.Security.Authentication;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tim.Manager.Db.Entities;
using Tim.Manager.Db.Repositories.PassItems;

namespace TimManager.Areas.Identity.Controllers
{
    [Area("Identity")]
    [Authorize]
    public class PassItemsController : Controller
    {
        private readonly IPassItemRepository _passItemRepository;
        private readonly UserManager<IdentityUser> _userManager;

        public PassItemsController(
            IPassItemRepository passItemRepository,
            UserManager<IdentityUser> userManager)

        {
            _passItemRepository = passItemRepository;
            _userManager = userManager;
        }

        // GET: Identity/PassItems
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IdentityUser user = await _userManager.GetUserAsync(HttpContext.User);
            List<PassItem> passItems = await _passItemRepository.GetPassItems(user.Id).ToListAsync();
            return View(passItems);
        }

        // GET: Identity/PassItems/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Identity/PassItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PassItem newPassItem)
        {
            ModelState.Remove(nameof(newPassItem.UserId));

            if (ModelState.IsValid)
            {
                try
                {
                    IdentityUser user = await _userManager.GetUserAsync(HttpContext.User);
                    newPassItem.UserId = user.Id;
                    newPassItem.User = user;

                    await _passItemRepository.InsertAsync(newPassItem);

                    return RedirectToAction(nameof(Index));
                }
                catch (InvalidOperationException ex)
                {
                    ModelState.AddModelError(ex.Data[PassItemRepository.ItemPropertyKey]?.ToString() ?? "", $"Unable to save changes. {ex.Message}.");
                }
            }

            return View(newPassItem);
        }

        // GET: Identity/PassItems/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            PassItem passItem = await GetPassItem(id);

            if (passItem == null)
            {
                return NotFound();
            }

            return View(passItem);
        }

        [HttpGet]
        public async Task<PassItem> GetPassItem(int id)
        {
            if (id == 0)
            {
                return null;
            }

            throwIfNotAuthenticated();
            PassItem passItem = await _passItemRepository.GetPassItemAsync(id);

            return passItem;
        }

        // POST: Identity/PassItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PassItem newPassItem)
        {
            ModelState.Remove(nameof(newPassItem.UserId));
            ModelState.Remove(nameof(newPassItem.Password));

            if (ModelState.IsValid)
            {
                try
                {
                    throwIfNotAuthenticated();

                    await _passItemRepository.UpdateAsync(newPassItem);
                    return RedirectToAction(nameof(Index));
                }
                catch (InvalidOperationException ex)
                {
                    ModelState.AddModelError(ex.Data[PassItemRepository.ItemPropertyKey]?.ToString() ?? "", $"Unable to save changes. {ex.Message}.");
                }
            }

            return View(newPassItem);
        }

        // GET: Identity/PassItems/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            throwIfNotAuthenticated();

            PassItem passItem = await GetPassItem(id);

            if (passItem == null)
            {
                return NotFound();
            }

            return View(passItem);
        }

        // POST: Identity/PassItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _passItemRepository.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private void throwIfNotAuthenticated()
        {
            if ((HttpContext.User == null) || !HttpContext.User.Identity.IsAuthenticated)
            {
                throw new AuthenticationException();
            }
        }
    }
}

TimManager/Views/Shared/HeaderPartial.cshtml
@using Tim.Manager.Db.Repositories.Identities;

@inject IUserManagerRepository manager;

@{ 
    var isSignedIn = manager.IsSignedIn(User);
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TimManager</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row d-flex">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (isSignedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-controller="PassItems" asp-action="Index" title="PasswordManager">Password manager</a>
                        </li>
                    }
                </ul>

                <ul class="navbar-nav">
                    @if (isSignedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

TimManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - TimManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @await Html.PartialAsync("HeaderPartial")

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TimManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>